name: CI

on:
  push:
    branches: [ main, master, nipt ]
  pull_request:
    branches: [ main, master, nipt ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  test-all:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
 
      - name: Manually install dependency
        run: sudo apt-get update -y && sudo apt-get install -y libcurl4-openssl-dev && sudo apt-get install -y libharfbuzz-dev && sudo apt-get install -y libfribidi-dev && which pkg-config

      - uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true

      - name: Install dependencies
        run:  export MAKE="make -j6" && sudo bash ./scripts/install-dependencies.sh

      - uses: r-lib/actions/check-r-package@v2
        with:
          working-directory: ./QUILT
          args: 'c("--no-manual", "--as-cran")'
          error-on: '"error"'
          upload-snapshots: true
          
      - name: Test the build
        run: ./scripts/build-and-install.R
        
      - name: Test README
        run: ./scripts/test-readme.sh

      - name: Test the CLI
        run: ./scripts/test-cli.R
 
      - name: QUILT1 Example test
        run: ./example/run_example.sh example/QUILT_usage.Md

      - name: HLA test
        run: ./scripts/run_hla_example.sh
