name: CI

on:
  push:
    branches: [ main, master, nipt ]
  pull_request:
    branches: [ main, master, nipt ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  test-all:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
 
      - name: Manually install dependency
        run: sudo apt-get update -y && sudo apt-get install -y build-essential libbz2-dev libcurl4-openssl-dev libssl-dev zlib1g-dev liblzma-dev libdeflate-dev libncurses5-dev curl autoconf git && which pkg-config && sudo apt-get install -y r-base r-cran-devtools

      - name: Install dependencies
        run: ./scripts/install-dependencies.sh

      - name: Test the build
        run: ./scripts/build-and-install.R
        
      - name: Test README
        run: ./scripts/test-readme.sh

      - name: Unit tests
        run: ./scripts/test-unit.sh

      - name: Acceptance tests
        run: ./scripts/test-acceptance.sh

      - name: Test the CLI
        run: ./scripts/test-cli.R
 
      - name: QUILT1 Example test
        run: ./example/run_example.sh example/QUILT_usage.Md

      - name: HLA test
        run: ./scripts/run_hla_example.sh
